using System.Collections.Generic;
using UnityEngine;
using NEXUS.Utilities;

/// <summary>
/// The template for an item. One asset per item name; quality is a per-instance
/// roll, not a separate asset.
///
/// Two shortswords are never identical: crafting rolls a quality tier and, on
/// top of that, a small variance band. That is why RollInstance() exists —
/// ToItem() gives the plain template version, RollInstance() gives the one a
/// smith actually produced.
/// </summary>
[CreateAssetMenu(fileName = "ItemSO", menuName = "Items/ItemSO")]
public class ItemSO : ScriptableObject
{
    [Header("Identity")]
    public int ID;
    public string itemName;
    [TextArea] public string description;

    [Tooltip("In-world line shown above the mechanical stats. Written as an " +
             "ability, not as a number: 'Your grip on the weapon has settled.'")]
    [TextArea(2, 4)] public string flavorText;

    [Header("Appearance")]
    public Sprite icon;

    [Header("Quality")]
    public ItemQuality quality = ItemQuality.Common;

    [Tooltip("One sprite per quality tier: Crude, Common, Fine, Masterwork, Legendary. " +
             "Missing entries fall back to icon.")]
    public List<Sprite> spritesByQuality = new();

    [Header("Economy")]
    public int goldValue;
    public int silverValue;

    [Header("Logistics")]
    [Min(0f)] public float weight = 1f;

    [Header("Stacking")]
    public bool stackable = true;
    [Min(1)] public int maxStack = 99;

    [Header("Classification")]
    public ItemCategory category = ItemCategory.Misc;

    [Tooltip("Leave as None to use the category's default slot.")]
    public EquipSlot slotOverride = EquipSlot.None;

    // ---------------------------------------------------------------
    // Weapon
    // ---------------------------------------------------------------

    [Header("Weapon")]
    public WeaponClass weaponClass = WeaponClass.None;
    public ScalingStat scaling = ScalingStat.Strength;

    [Tooltip("Number of damage dice, e.g. 1 in '1d8'.")]
    [Min(0)] public int damageDiceCount = 1;

    [Tooltip("Die size, e.g. 8 in '1d8'. 0 for non-weapons.")]
    [Min(0)] public int damageDie = 0;

    [Tooltip("Occupies both hands — locks the off-hand slot.")]
    public bool twoHanded = false;

    // ---------------------------------------------------------------
    // Armour
    // ---------------------------------------------------------------

    [Header("Armour")]
    [Min(0)] public int armorValue = 0;
    public ArmorWeight armorWeight = ArmorWeight.None;

    // ---------------------------------------------------------------
    // Consumable
    // ---------------------------------------------------------------

    [Header("Consumable")]
    public int healthRecovery = 0;
    public int exhaustionReduction = 0;
    public int rationValue = 0;

    // ---------------------------------------------------------------
    // Effects
    // ---------------------------------------------------------------

    [Header("Modifiers")]
    public List<StatModifier> modifiers = new List<StatModifier>();

    [Tooltip("Percent spread applied to rolled instances. 15 means a crafted " +
             "item lands anywhere from -15% to +15% of the template values, " +
             "so two shortswords from the same recipe differ.")]
    [Range(0, 50)] public int varianceP = 15;

    [Header("Rarity")]
    [Tooltip("Rare, witch-made charms. Magic never appears in combat — only in events.")]
    public bool isMagical = false;
    [TextArea] public string magicalEffect = "";

    [Tooltip("Exactly one exists in the world. Never generated by crafting or shops.")]
    public bool isUnique = false;

    [Header("Crafting")]
    [Tooltip("Trinkets and quest items are found, never made.")]
    public bool craftable = true;

    // ---------------------------------------------------------------
    // Derived
    // ---------------------------------------------------------------

    public bool IsPotion => category == ItemCategory.Potion;
    public bool IsConsumable => category == ItemCategory.Potion || category == ItemCategory.Consumable;
    public bool IsWeapon => category == ItemCategory.Weapon;
    public bool IsEquippable => ItemRules.IsEquippable(category);

    public EquipSlot Slot =>
        slotOverride != EquipSlot.None ? slotOverride : ItemRules.DefaultSlot(category);

    public bool CanGoInOffHand =>
        category == ItemCategory.Shield ||
        (IsWeapon && ItemRules.CanDualWield(weaponClass, twoHanded));

    public string DamageNotation =>
        damageDie <= 0 ? "—" : $"{Mathf.Max(1, damageDiceCount)}d{damageDie}";

    public Currency GetBaseValue() => new Currency(goldValue, silverValue);

    public Sprite GetSpriteForQuality(ItemQuality q)
    {
        if (spritesByQuality == null || spritesByQuality.Count == 0) return icon;

        int i = Mathf.Clamp((int)q, 0, spritesByQuality.Count - 1);
        return spritesByQuality[i] != null ? spritesByQuality[i] : icon;
    }

    public int GetMultiplier(ItemQuality q) => ItemRules.Multiplier(q);

    /// <summary>Damage roll for one swing, before the ability modifier.</summary>
    public int RollDamage()
    {
        if (damageDie <= 0) return 0;

        int total = 0;
        for (int i = 0; i < Mathf.Max(1, damageDiceCount); i++)
            total += Dice.Roll(damageDie);

        return total;
    }

    /// <summary>Which attribute value this weapon scales from.</summary>
    public int GetScalingValue(int strength, int dexterity)
    {
        switch (scaling)
        {
            case ScalingStat.Dexterity: return dexterity;
            case ScalingStat.Hybrid:    return Mathf.RoundToInt((strength + dexterity) / 2f);
            default:                    return strength;
        }
    }

    // ---------------------------------------------------------------
    // Instantiation
    // ---------------------------------------------------------------

    /// <summary>Plain template copy at the asset's own quality.</summary>
    public Item ToItem(int quantity = 1) => BuildItem(quality, 100, quantity);

    /// <summary>
    /// A crafted or looted instance. Quality shifts the values by its tier
    /// multiplier, then variance decides where inside the band this particular
    /// piece landed — the reason one shortsword gives +3 and the next gives +1.
    /// </summary>
    public Item RollInstance(ItemQuality rolledQuality, int quantity = 1)
    {
        int spread = Mathf.Max(0, varianceP);
        int roll = spread == 0 ? 0 : Dice.Roll(-spread, spread + 1);
        int percent = ItemRules.Multiplier(rolledQuality) + roll;

        return BuildItem(rolledQuality, Mathf.Max(10, percent), quantity);
    }

    /// <summary>
    /// An instance made at a forge, carrying the two rolled properties that
    /// separate a smith's work from a shop's stock.
    ///
    /// Shop goods deliberately do not get these — mass-produced work is
    /// unremarkable, and that is what leaves the forge worth using.
    /// </summary>
    public Item CraftInstance(ItemQuality rolledQuality, int craftLevel, int quantity = 1)
    {
        var item = RollInstance(rolledQuality, quantity);
        if (item == null) return null;

        item.HiddenEffects = CraftedStatRoller.Roll(category, rolledQuality, craftLevel);
        return item;
    }

    private Item BuildItem(ItemQuality q, int percent, int quantity)
    {
        int finalQuantity = Mathf.Max(1, quantity);
        Sprite sprite = GetSpriteForQuality(q);
        int qIndex = (int)q;

        int scaledGold = Mathf.RoundToInt(goldValue * percent / 100f);
        int scaledSilver = Mathf.RoundToInt(silverValue * percent / 100f);

        Item created;

        if (IsConsumable)
        {
            created = new Item(
                ID, itemName, scaledGold, scaledSilver,
                healthRecovery, exhaustionReduction,
                sprite, qIndex, finalQuantity, stackable, maxStack, weight);
        }
        else if (modifiers != null && modifiers.Count > 0)
        {
            var scaledMods = new List<StatModifier>(modifiers.Count);
            foreach (var m in modifiers)
            {
                int value = Mathf.RoundToInt(m.Value * percent / 100f);

                // A modifier authored as non-zero must never round away to
                // nothing — a Crude sword is worse, not inert.
                if (m.Value != 0 && value == 0)
                    value = m.Value > 0 ? 1 : -1;

                scaledMods.Add(new StatModifier(m.Type, value, itemName));
            }

            created = new Item(
                ID, itemName, scaledGold, scaledSilver,
                category, scaledMods,
                sprite, qIndex, finalQuantity, stackable, maxStack, weight);
        }
        else
        {
            created = new Item(
                ID, itemName, scaledGold, scaledSilver,
                category, finalQuantity, stackable, maxStack, weight);
        }

        if (created != null)
            created.IsMagical = isMagical;

        return created;
    }
}
